### ISSUE TITLE
Fix cmake issues

### ISSUE THREAD

**Issue by thomasfire** [rbetik12/RightEngine2D#1]
I have found, that RightEngine2D/Game/CMakeLists.txt contains a huge pack of files to compile in monoline. Also, what is the purpose of including headers into the build target, if they are all included and compiled with the cpp files?

**Comment by thomasfire** [comment]
Also it worth to check other cmake's for this style problem

**Comment by rbetik12** [comment]
I guess it's fixed now

**Comment by thomasfire** [comment]
The headers are still in targets. That leads to double compilation of the same files
